baseUrl = "https://justin1dennison.github.io/blog/"
languageCode = "en-us"
title = "Justin's Musings"
theme = "ananke"
googleAnalytics="UA-159569087-1"
sectionPagesMenu = "main"


[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10